version: '3.7'
services:

  nginx:
   image: nginx

   ports:
   - 8010:8010
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - masya_server

  masya_server:
    container_name: masya_server
    hostname: masya_server

    restart: always
    volumes:
      - ./:/server
      - ~/.m2:/root/.m2
    build:
      context: .
      dockerfile: Dockerfile
    command: mvn clean spring-boot:run